### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: 'Error reading JObject from JsonReader. Path '', line 0, position 0.' 

### ISSUE THREAD

**Issue by hakkietem350** [thodex-exchange/thodex-vbnet-api#3] opened 2020-12-02 19:22 UTC
Adding api and secret key doesnt change anything it still gives same error as i said

**Comment by letreset** [comment] 2020-12-04 20:36
This error caused by a mismatch of the security binding between the client and the server. Fixed with this commit
https://github.com/thodex-exchange/thodex-vbnet-api/commit/66928da6d36a8eeed721bfb25dbfac7c9f41c5c9

**Closed as completed by letreset** 2020-12-04 20:36 UTC
